apiVersion: v1
kind: Service
metadata:
  name: company-app-svc
  labels:
    app: company
    tier: app
    version: v1
spec:
  type: ClusterIP # LoadBalancer
  ports:
    - port: 80
  selector:
    app: company
    tier: app
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-app-dep
  labels:
    app: company
    tier: app
    version: v1
spec:
  selector:
    matchLabels:
      app: company
      tier: app
      version: v1
  replicas: 2
  template:
    metadata:
      labels:
        app: company
        tier: app
        version: v1
    spec:
      containers:
        - name: company
          image: jcmds/company:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 25m
              memory: 200Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
